<?php
declare(strict_types=1);

namespace Quiote\Routing\Compiler;

use Quiote\Config\Config;
use Quiote\Support\Compiler\EmittedArtifact;

/**
 * Dumps/loads the routing IR (a RoutePlan's RouteDefinitions) as an
 * opcache-friendly `return [...]` PHP artifact, so AttributeRouting::build()
 * can skip AttributeRouteScanner's live scan (recursive glob() per module
 * Actions/ tree, require_once + ReflectionClass per action class) on every
 * Routing construction -- a per-request cost under classic PHP-FPM.
 *
 * Unlike CompiledMatcherDumper, this artifact cannot be keyed by a signature
 * of the *built* routes: the whole point is to avoid building them. It's
 * instead keyed by the scan *inputs* (module directories + namespace prefix)
 * -- the same values AttributeRouteScanner::scan() itself defaults to -- and
 * trusted unconditionally once written, gated by core.routing.trust_compiled_ir
 * (default false; set true in production after `cache:warmup`, mirroring
 * core.config_check_freshness's "trust the cache" contract from item 7).
 * @since      1.0.0
 */
final class RoutingIrDumper
{
    /**
     * The path the routing IR artifact is written to / loaded from, keyed by
     * the default scan inputs (core.module_dir + plugin module directories +
     * core.namespace_prefix). A Routing subclass overriding moduleDirs() to
     * something non-default is never covered by this artifact -- callers
     * must check that themselves before relying on it (see
     * AttributeRouting::build()).
     */
    public static function targetFor(): string
    {
        $moduleDirs = [Config::getString('core.module_dir'), ...\Quiote\Plugin\PluginManager::moduleDirectories()];
        $namespacePrefix = Config::getString('core.namespace_prefix', 'App');
        $key = md5(implode('|', $moduleDirs) . '#' . $namespacePrefix);
        return rtrim(Config::getString('core.cache_dir'), '/') . '/routing/RoutingIr_' . $key . '.php';
    }

    /**
     * Emit the routing IR PHP (a file that `return`s a plain array
     * reconstructible into a RoutePlan by load()), without writing it.
     */
    public static function emit(RoutePlan $plan): EmittedArtifact
    {
        $rows = [];
        foreach ($plan->routes as $route) {
            $rows[] = [
                'name' => $route->name,
                'path' => $route->path,
                'module' => $route->module,
                'action' => $route->action,
                'methods' => $route->methods,
                'defaults' => $route->defaults,
                'requirements' => $route->requirements,
                'host' => $route->host,
                'condition' => $route->condition,
                'priority' => $route->priority,
                'outputType' => $route->outputType,
                'meta' => $route->meta,
                'sourceRef' => $route->sourceRef,
            ];
        }
        $data = [
            'sourceRef' => $plan->sourceRef,
            'routes' => $rows,
        ];
        $php = "<?php\n\n"
            . "// Compiled routing IR -- generated by `quiote cache:warmup`.\n"
            . "// Do not edit by hand; regenerate after changing #[Route] attributes.\n"
            . 'return ' . var_export($data, true) . ";\n";

        return EmittedArtifact::fromSource($php, self::targetFor());
    }

    /**
     * Load a previously dumped routing IR artifact, or null if none exists or
     * it's malformed (a bad/stale artifact must never break routing -- the
     * caller falls back to a live scan).
     */
    public static function load(): ?RoutePlan
    {
        $path = self::targetFor();
        if (!is_file($path)) {
            return null;
        }
        try {
            $data = include $path;
        } catch (\Throwable) {
            return null;
        }
        if (!is_array($data) || !isset($data['sourceRef'], $data['routes']) || !is_string($data['sourceRef']) || !is_array($data['routes'])) {
            return null;
        }

        $routes = [];
        foreach ($data['routes'] as $row) {
            if (!is_array($row)) {
                return null;
            }
            $routes[] = new RouteDefinition(
                self::stringOf($row['name'] ?? null),
                self::stringOf($row['path'] ?? null),
                self::stringOf($row['module'] ?? null),
                self::stringOf($row['action'] ?? null),
                self::listOf($row['methods'] ?? null),
                self::mapOf($row['defaults'] ?? null),
                self::stringMapOf($row['requirements'] ?? null),
                self::nullableStringOf($row['host'] ?? null),
                self::nullableStringOf($row['condition'] ?? null),
                self::intOf($row['priority'] ?? null),
                self::nullableStringOf($row['outputType'] ?? null),
                self::routeMetaOf($row['meta'] ?? null, self::stringOf($row['path'] ?? null)),
                self::stringOf($row['sourceRef'] ?? null),
            );
        }

        return new RoutePlan($routes, $data['sourceRef']);
    }

    private static function stringOf(mixed $value): string
    {
        return is_string($value) ? $value : '';
    }

    private static function nullableStringOf(mixed $value): ?string
    {
        return is_string($value) ? $value : null;
    }

    private static function intOf(mixed $value): int
    {
        return is_int($value) ? $value : 0;
    }

    /** @return array<int,string> */
    private static function listOf(mixed $value): array
    {
        if (!is_array($value)) {
            return [];
        }
        $out = [];
        foreach ($value as $v) {
            if (is_string($v)) {
                $out[] = $v;
            }
        }
        return $out;
    }

    /** @return array<string,mixed> */
    private static function mapOf(mixed $value): array
    {
        return is_array($value) ? $value : [];
    }

    /** @return array<string,string> */
    private static function stringMapOf(mixed $value): array
    {
        if (!is_array($value)) {
            return [];
        }
        $out = [];
        foreach ($value as $k => $v) {
            if (is_string($k) && is_string($v)) {
                $out[$k] = $v;
            }
        }
        return $out;
    }

    /**
     * @return array{gen_path:string,cut:bool,path:string}
     */
    private static function routeMetaOf(mixed $value, string $fallbackPath): array
    {
        $genPath = $fallbackPath;
        $cut = false;
        $path = $fallbackPath;
        if (is_array($value)) {
            if (isset($value['gen_path']) && is_string($value['gen_path'])) {
                $genPath = $value['gen_path'];
            }
            if (isset($value['cut'])) {
                $cut = (bool) $value['cut'];
            }
            if (isset($value['path']) && is_string($value['path'])) {
                $path = $value['path'];
            }
        }
        return ['gen_path' => $genPath, 'cut' => $cut, 'path' => $path];
    }
}
