<?php
namespace Quiote\Validator\Compiler;

use Quiote\Validator\AndoperatorValidator;
use Quiote\Validator\BooleanValidator;
use Quiote\Validator\Compiler\Ir\ValidatorNode;
use Quiote\Validator\Compiler\Ir\ValidatorPlan;
use Quiote\Validator\Compiler\Runtime\ValidatorBuilder;
use Quiote\Validator\EmailValidator;
use Quiote\Validator\InarrayValidator;
use Quiote\Validator\IsNotEmptyValidator;
use Quiote\Validator\IssetValidator;
use Quiote\Validator\JsonValidator;
use Quiote\Validator\NotoperatorValidator;
use Quiote\Validator\NumberValidator;
use Quiote\Validator\OroperatorValidator;
use Quiote\Validator\RegexValidator;
use Quiote\Validator\StringValidator;
use Quiote\Validator\Validator;
use Quiote\Validator\XoroperatorValidator;

/**
 * Emits a ValidatorPlan as committable, opcacheable PHP source that returns
 * a closure over Quiote\Validator\Compiler\Runtime\ValidatorBuilder --
 * the same format a developer can hand-write for a validator that never
 * had an XML config at all (see docs/VALIDATOR_COMPILER_PLAN.md phase 3).
 *
 * Every parameter reaching this emitter already passed
 * ValidatorPlanBuilder's compile-time whitelist check (assuming the
 * default 'throw'/'warn' mode), so an "unmappable" parameter here is never
 * a bogus one -- it's a real, accepted parameter this emitter's fluent
 * vocabulary hasn't grown a dedicated method for yet. That's exactly the
 * case that gets flagged (Diagnostic::CODE_UNMAPPABLE_PARAMETER) rather
 * than silently handled: the payoff of this emitter, mirroring the
 * compile-time check, is surfacing exactly the shape of gap that let a
 * nonexistent allowlist attribute go unenforced in the incident that
 * motivated this compiler.
 *
 * Whenever the "pretty" fluent shortcut doesn't cleanly apply (a name
 * override, a non-default source/base, multiple/named arguments, custom
 * error messages, or any class/parameter this emitter doesn't have a
 * dedicated mapping for), it falls back to ValidatorBuilder::raw() with
 * the full, untouched arguments/parameters/errors from the IR node --
 * this fallback is always behaviorally complete, so a coverage gap in the
 * "pretty" mapping can never mean a validator's behavior is silently
 * dropped from the generated file.
 * @since      1.0.0
 */
class FluentSourceEmitter implements EmitterInterface
{
	/**
	 * class => [factory method name, [param name => spec setter method]].
	 * Only used for classes whose constructor argument is a single request
	 * parameter name plus a `required` flag -- InarrayValidator and
	 * RegexValidator are handled separately since their factory methods
	 * take an extra positional argument (values / pattern+match).
	 */
	private const SIMPLE_FACTORY = [
		StringValidator::class => ['string', ['min' => 'minLength', 'max' => 'maxLength', 'trim' => 'trim', 'utf8' => 'utf8']],
		EmailValidator::class => ['email', []],
		NumberValidator::class => ['number', ['min' => 'min', 'max' => 'max', 'type' => 'type', 'cast_to' => 'castTo']],
		BooleanValidator::class => ['boolean', []],
		IsNotEmptyValidator::class => ['isNotEmpty', []],
		IssetValidator::class => ['isSet', []],
		JsonValidator::class => ['json', []],
	];

	private const OPERATOR_CLASSES = [
		AndoperatorValidator::class => 'and',
		OroperatorValidator::class => 'or',
		NotoperatorValidator::class => 'not',
		XoroperatorValidator::class => 'xor',
	];

	/** @var Diagnostic[] */
	private array $diagnostics = [];

	public function emit(ValidatorPlan $plan): EmittedArtifact
	{
		$this->diagnostics = [];

		$body = [];
		foreach ($plan->nodes as $node) {
			foreach ($this->emitNode($node, 1) as $line) {
				$body[] = $line;
			}
		}

		$checksum = hash('sha256', $plan->sourceRef . "\0" . implode("\n", array_map(fn($n) => $this->fingerprint($n), $plan->nodes)));

		$lines = [];
		$lines[] = '<?php';
		$lines[] = '// @generated by the Quiote validator compiler -- do not edit by hand.';
		$lines[] = '// Regenerate from: ' . $plan->sourceRef;
		$lines[] = '// source-fingerprint: ' . $checksum;
		$lines[] = '';
		$lines[] = 'return static function (' . '\\' . ValidatorBuilder::class . ' $v): void {';
		foreach ($body as $line) {
			$lines[] = $line;
		}
		$lines[] = '};';
		$lines[] = '';

		$source = implode("\n", $lines);

		return new EmittedArtifact($source, hash('sha256', $source), $this->targetHintFor($plan->sourceRef));
	}

	/**
	 * @return Diagnostic[] Diagnostics recorded during the last emit() call.
	 */
	public function getDiagnostics(): array
	{
		return $this->diagnostics;
	}

	/**
	 * @return string[] PHP source lines for this node (and, recursively, its children).
	 */
	private function emitNode(ValidatorNode $node, int $depth): array
	{
		if (isset(self::OPERATOR_CLASSES[$node->validatorClass]) && $this->isSimpleOperator($node)) {
			return $this->emitOperator($node, $depth);
		}

		if ($node->validatorClass === InarrayValidator::class && $this->isSimpleEnum($node)) {
			return $this->emitEnum($node, $depth);
		}

		if ($node->validatorClass === RegexValidator::class && $this->isSimpleRegex($node)) {
			return $this->emitRegex($node, $depth);
		}

		if (isset(self::SIMPLE_FACTORY[$node->validatorClass]) && $this->isSimpleLeaf($node, self::SIMPLE_FACTORY[$node->validatorClass][1])) {
			return $this->emitSimpleLeaf($node, $depth);
		}

		return $this->emitRaw($node, $depth);
	}

	// -- simplicity predicates -------------------------------------------------

	private function hasOnlyGenericChainable(ValidatorNode $node, array $classSpecificKeys): bool
	{
		$structural = ['class', 'method', 'required'];
		$chainableGeneric = ['severity', 'export', 'translation_domain'];
		$allowed = array_merge($structural, $chainableGeneric, $classSpecificKeys);
		$extra = array_diff(array_keys($node->parameters), $allowed);
		return empty($extra);
	}

	private function isSimpleLeaf(ValidatorNode $node, array $classSpecificKeys): bool
	{
		return $node->base === ''
			&& count($node->arguments) === 1
			&& array_is_list($node->arguments)
			&& $node->arguments[0] !== ''
			&& empty($node->children)
			&& empty($node->errors)
			&& $this->hasOnlyGenericChainable($node, array_keys($classSpecificKeys));
	}

	private function isSimpleEnum(ValidatorNode $node): bool
	{
		if (!$this->isSimpleLeaf($node, ['values' => true, 'sep' => true, 'case' => true, 'strict' => true])) {
			return false;
		}
		$sep = $node->parameters['sep'] ?? ',';
		return $sep === ',' && array_key_exists('values', $node->parameters);
	}

	private function isSimpleRegex(ValidatorNode $node): bool
	{
		if (!$this->isSimpleLeaf($node, ['pattern' => true, 'match' => true])) {
			return false;
		}
		return array_key_exists('pattern', $node->parameters);
	}

	private function isSimpleOperator(ValidatorNode $node): bool
	{
		$specific = $node->validatorClass === AndoperatorValidator::class || $node->validatorClass === OroperatorValidator::class
			? ['break']
			: [];
		// An operator itself is "simple" purely based on its own base/params;
		// its children are emitted recursively regardless of whether each
		// one takes the fluent or the raw() path, so no per-child check is
		// needed here.
		return $node->base === '' && $this->hasOnlyGenericChainable($node, array_merge($specific, ['skip_errors']));
	}

	// -- emission ---------------------------------------------------------------

	private function emitSimpleLeaf(ValidatorNode $node, int $depth): array
	{
		[$factoryMethod, $paramMap] = self::SIMPLE_FACTORY[$node->validatorClass];
		$required = $this->literal($node->parameters['required'] ?? true);
		$argument = $this->literal($node->arguments[0]);

		$expr = sprintf('$v->%s(%s, %s)', $factoryMethod, $argument, $required);
		return $this->wrapWithChain($node, $expr, $paramMap, $depth);
	}

	private function emitEnum(ValidatorNode $node, int $depth): array
	{
		$required = $this->literal($node->parameters['required'] ?? true);
		$argument = $this->literal($node->arguments[0]);
		$values = $this->literal($node->parameters['values']);

		$expr = sprintf('$v->enum(%s, %s, %s)', $argument, $values, $required);
		return $this->wrapWithChain($node, $expr, ['case' => 'caseSensitive', 'strict' => 'strict'], $depth);
	}

	private function emitRegex(ValidatorNode $node, int $depth): array
	{
		$required = $this->literal($node->parameters['required'] ?? true);
		$argument = $this->literal($node->arguments[0]);
		$pattern = $this->literal($node->parameters['pattern']);
		$match = $this->literal($node->parameters['match'] ?? true);

		$expr = sprintf('$v->regex(%s, %s, %s, %s)', $argument, $pattern, $match, $required);
		return $this->wrapWithChain($node, $expr, [], $depth);
	}

	private function wrapWithChain(ValidatorNode $node, string $expr, array $paramMap, int $depth): array
	{
		$indent = str_repeat('    ', $depth);
		$chain = [$expr];

		foreach ($paramMap as $paramName => $method) {
			if (!array_key_exists($paramName, $node->parameters)) {
				continue;
			}
			$chain[] = sprintf('->%s(%s)', $method, $this->literal($node->parameters[$paramName]));
		}
		if (($node->parameters['severity'] ?? 'error') !== 'error') {
			$chain[] = sprintf('->severity(%s)', $this->literal($node->parameters['severity']));
		}
		if (!empty($node->parameters['export']) && is_string($node->parameters['export'])) {
			$chain[] = sprintf('->export(%s)', $this->literal($node->parameters['export']));
		}
		if (!empty($node->parameters['translation_domain'])) {
			$chain[] = sprintf('->translationDomain(%s)', $this->literal($node->parameters['translation_domain']));
		}

		return [$indent . implode('', $chain) . ';'];
	}

	private function emitOperator(ValidatorNode $node, int $depth): array
	{
		$indent = str_repeat('    ', $depth);
		$operator = self::OPERATOR_CLASSES[$node->validatorClass];

		$lines = [];
		$lines[] = sprintf('%s$v->group(%s, function (\%s $v): void {', $indent, $this->literal($operator), ValidatorBuilder::class);
		foreach ($node->children as $child) {
			foreach ($this->emitNode($child, $depth + 1) as $line) {
				$lines[] = $line;
			}
		}
		$tail = '})';
		if (($node->parameters['skip_errors'] ?? false)) {
			$tail .= sprintf('->skipErrors(%s)', $this->literal($node->parameters['skip_errors']));
		}
		if (($node->parameters['break'] ?? false)) {
			$tail .= sprintf('->breakOnFirst(%s)', $this->literal($node->parameters['break']));
		}
		if (($node->parameters['severity'] ?? 'error') !== 'error') {
			$tail .= sprintf('->severity(%s)', $this->literal($node->parameters['severity']));
		}
		$lines[] = $indent . $tail . ';';

		return $lines;
	}

	private function emitRaw(ValidatorNode $node, int $depth): array
	{
		$indent = str_repeat('    ', $depth);

		$reason = class_exists($node->validatorClass) && is_subclass_of($node->validatorClass, Validator::class)
			? sprintf('parameters/shape of "%s" not covered by a dedicated fluent mapping yet', $node->validatorClass)
			: sprintf('"%s" is not a recognized Validator subclass at emit time', $node->validatorClass);

		$this->diagnostics[] = new Diagnostic(
			Diagnostic::SEVERITY_WARNING,
			Diagnostic::CODE_UNMAPPABLE_PARAMETER,
			sprintf('Validator "%s" (%s) falls back to raw(): %s.', $node->name, $node->validatorClass, $reason),
			$node->name
		);

		$hasChildren = !empty($node->children);
		$call = sprintf(
			'$v->raw(%s, %s, %s, %s%s)',
			$this->literal($node->validatorClass),
			$this->literal(array_values($node->arguments)),
			$this->literal($node->parameters),
			$this->literal($node->errors),
			$hasChildren ? sprintf(', function (\%s $v): void {', ValidatorBuilder::class) : ''
		);

		if (!$hasChildren) {
			return [$indent . '// fluent mapping unavailable for this validator; see diagnostics', $indent . $call . ';'];
		}

		$lines = [$indent . '// fluent mapping unavailable for this validator; see diagnostics', $indent . $call];
		foreach ($node->children as $child) {
			foreach ($this->emitNode($child, $depth + 1) as $line) {
				$lines[] = $line;
			}
		}
		$lines[] = $indent . '});';

		return $lines;
	}

	private function literal(mixed $value): string
	{
		return var_export($value, true);
	}

	private function fingerprint(ValidatorNode $node): string
	{
		$parts = [$node->name, $node->validatorClass, $node->base, implode(',', $node->methods)];
		$parts[] = json_encode($node->arguments);
		$parts[] = json_encode($node->parameters);
		$parts[] = json_encode($node->errors);
		foreach ($node->children as $child) {
			$parts[] = $this->fingerprint($child);
		}
		return implode('|', $parts);
	}

	private function targetHintFor(string $sourceRef): string
	{
		$base = preg_replace('/\.xml$/i', '', basename($sourceRef));
		return ($base !== '' ? $base : 'validators') . '.generated.php';
	}
}
