<?php
namespace Quiote\Routing;

use Quiote\Context;
use Quiote\Util\ParameterHolder;
use Symfony\Contracts\Service\ResetInterface;

/**
 * RoutingCallback allows you to provide callbacks into the routing
 * @since      1.0.0
 * @version    1.0.0
 */
abstract class RoutingCallback extends ParameterHolder implements ResetInterface
{
	/**
	 * @var        ?Context An Context instance.
	 */
	protected $context = null;

	/**
	 * @var        ?array<mixed, mixed> An array with information about the route.
	 */
	protected $route = null;

	/**
	 * Initialize the callback instance.
	 * @param      Context $context An Context instance.
	 * @param      array<mixed, mixed>   $route   An array with information about the route.
	 * @return     void
	 * @since      1.0.0
	 */
	public function initialize(Context $context, array &$route)
	{
		$this->context = $context;
		$this->route =& $route;
	}

	/**
	 * Retrieve the current application context.
	 * @return     Context An Context instance.
	 * @since      1.0.0
	 */
	public final function getContext()
	{
		return $this->context;
	}

	/**
	 * Executed when the route matched (container-less). Return false to reject match.
	 * @param array<string, mixed> $parameters Parameters generated by this route (modifiable).
	 * @param mixed $legacyContainer Unused; retained for signature compatibility.
	 * @return bool true to accept match; false to treat as not matched.
	 * @since      1.0.0
	 */
	public function onMatched(array &$parameters, $legacyContainer = null)
	{
		return true;
	}

	/**
	 * Executed when the route did NOT match (container-less).
	 * @param mixed $legacyContainer Unused; retained for signature compatibility.
	 * @return void
	 * @since      1.0.0
	 */
	public function onNotMatched($legacyContainer = null)
	{
		return;
	}

	/**
	 * Gets executed when the route of this callback is about to be reverse
	 * generated into an URL.
	 * @param      array<mixed, mixed> $defaultParameters The default parameters stored in the route.
	 * @param      array<mixed, mixed> $userParameters The parameters the user supplied to Routing::gen().
	 * @param      array<mixed, mixed> $userOptions The options the user supplied to Routing::gen().
	 * @return     bool  Whether this route part should be generated.
	 * @since      1.0.0
	 */
	public function onGenerate(array $defaultParameters, array &$userParameters, array &$userOptions)
	{
		return true;
	}

	#[\Override]
    public function reset() : void
	{
		$this->context = null;
		$this->route = null;
		$this->clearParameters();
	}
}

?>