<?php
use Quiote\Config\ConfigHandler;

class ImportTestOnceHandler extends ConfigHandler
{
	public function execute($config, $context = null)
	{
		$code = '$GLOBALS["ConfigCacheImportTestOnce_included"] = true;';

		// compile data
		$retval = "<?php\n" .
				  "// auto-generated by AutoloadConfigHandler\n" .
				  "// date: %s\n%s\n?>";
		$retval = sprintf($retval, date('m/d/Y H:i:s'), $code);

		return $retval;

	}

}

?>