<?php
use Quiote\Config\ConfigHandler;

class ImportTestHandler extends ConfigHandler
{
	public function execute($config, $context = null)
	{
		$code = 'if (!defined("ConfigCacheImportTest_included")) { define("ConfigCacheImportTest_included", true); }';

		// compile data
		$retval = "<?php\n" .
				  "// auto-generated by AutoloadConfigHandler\n" .
				  "// date: %s\n%s\n?>";
		$retval = sprintf($retval, date('m/d/Y H:i:s'), $code);

		return $retval;

	}

}

?>