<?php

// +---------------------------------------------------------------------------+
// | This file is part of the Agavi package.                                   |
// | Copyright (c) 2005-2011 the Agavi Project.                                |
// | Based on the Mojavi3 MVC Framework, Copyright (c) 2003-2005 Sean Kerr.    |
// |                                                                           |
// | For the full copyright and license information, please view the LICENSE   |
// | file that was distributed with this source code. You can also view the    |
// | LICENSE file online at http://www.agavi.org/LICENSE.txt                   |
// |   vi: set noexpandtab:                                                    |
// |   Local Variables:                                                        |
// |   indent-tabs-mode: t                                                     |
// |   End:                                                                    |
// +---------------------------------------------------------------------------+
namespace Agavi\Config;

use Agavi\Util\AgaviParameterHolder;
use Agavi\Util\AgaviToolkit;

/**
 * AgaviBaseConfigHandler allows a developer to create a custom formatted
 * configuration file pertaining to any information they like and still
 * have it auto-generate PHP code.
 *
 * @package    agavi
 * @subpackage config
 *
 * @author     Sean Kerr <skerr@mojavi.org>
 * @author     Dominik del Bondio <ddb@bitxtender.com>
 * @author     David Zülke <dz@bitxtender.com>
 * @copyright  Authors
 * @copyright  The Agavi Project
 *
 * @since      0.11.0
 *
 * @version    $Id$
 */
abstract class AgaviBaseConfigHandler extends AgaviParameterHolder
{
	/**
	 * Generate the code for returning from execute().
	 *
	 * @param      mixed A string with the code, or an array of code lines.
	 * @param      string An optional config file path, to be put in a comment.
	 *
	 * @return     string PHP code.
	 *
	 * @author     David Zülke <dz@bitxtender.com>
	 * @since      0.11.0
	 */
	protected function generate($code, $path = null)
	{
		if(is_array($code)) {
			$code = implode("\n", $code);
		}
		
		// Intentionally omit the closing PHP tag to avoid accidental whitespace output
		// which can break header operations (e.g., session_start, setcookie) in worker mode.
		// We previously always appended an extra semicolon, which resulted in ';;' when the
		// provided code already ended with a semicolon (common, e.g. 'return array(...);').
		// Only append a semicolon if the last non-whitespace character is not one that
		// normally terminates a PHP statement or block.
		$trimmed = rtrim((string) $code);
		if($trimmed !== '' && !preg_match('/[;}\]]$/', $trimmed)) {
			$code = $trimmed . ';';
		} else {
			$code = $trimmed; // ensure consistent trailing whitespace handling
		}
		return sprintf(
			"<?php\n\n// This is a compiled Agavi configuration file\n// Compiled from: %s\n// Generated by: %s\n// Date: %s\n\n%s\n",
			$path ?? '(unknown)',
			static::class,
			gmdate(\DateTime::ATOM),
			$code
		);
	}
	
	/**
     * Literalize a string value.
     *
     * @param      string The value to literalize.
     *
     * @return     string A literalized value.
     *
     * @author     Sean Kerr <skerr@mojavi.org>
     * @author     Dominik del Bondio <ddb@bitxtender.com>
     * @author     David Zülke <dz@bitxtender.com>
     * @since      0.9.0
     */
    #[\Deprecated(message: 'Use AgaviToolkit::expandDirectives() instead.')]
    public static function literalize($value)
	{
		return AgaviToolkit::literalize($value);
	}

	/**
     * Replace configuration directive identifiers in a string.
     *
     * @param      string The value on which to run the replacement procedure.
     *
     * @return     string The new value.
     *
     * @author     Sean Kerr <skerr@mojavi.org>
     * @author     Johan Mjones <johan.mjones@ongame.com>
     * @author     David Zülke <dz@bitxtender.com>
     * @since      0.9.0
     */
    #[\Deprecated(message: 'Use AgaviToolkit::expandDirectives() instead.')]
    public static function replaceConstants($value)
	{
		return AgaviToolkit::expandDirectives($value);
	}

	/**
	 * Replace a relative filesystem path with an absolute one.
	 *
	 * @param      string A relative filesystem path.
	 *
	 * @return     string The new path.
	 *
	 * @author     Sean Kerr <skerr@mojavi.org>
	 * @since      0.9.0
	 */
	public static function replacePath($path)
	{
		if(!AgaviToolkit::isPathAbsolute($path)) {
			// not an absolute path so we'll prepend to it
			$path = AgaviConfig::get('core.app_dir') . '/' . $path;
		}

		return $path;
	}
}
