<?php

use Quiote\Config\CompiledArtifact;
use Quiote\Exception\CacheException;
use Quiote\Testing\PhpUnitTestCase;

/**
 * The compiled cache file: a header plus a single `return <literal>;`. Serializing a handler's
 * declaration happens here, so this is where "a cache entry can only hand back data" is enforced.
 */
class CompiledArtifactTest extends PhpUnitTestCase
{
	private function roundTrip(mixed $value): mixed
	{
		$file = tempnam(sys_get_temp_dir(), 'cat_');
		if ($file === false) {
			throw new \RuntimeException('Failed to create a temporary file.');
		}
		file_put_contents($file, CompiledArtifact::source($value, '/tmp/foo.xml', 'TestHandler'));
		try {
			return include $file;
		} finally {
			unlink($file);
		}
	}

	public function testTheArtifactNamesItsSourceAndItsHandler(): void
	{
		$source = CompiledArtifact::source(['a' => 1], '/tmp/foo.xml', 'TestHandler');

		$this->assertStringStartsWith("<?php\n", $source);
		$this->assertStringContainsString('// Compiled from: /tmp/foo.xml', $source);
		$this->assertStringContainsString('// Generated by: TestHandler', $source);
		$this->assertStringContainsString("return array (\n  'a' => 1,\n);", $source);
	}

	public function testAnUnknownSourceAndHandlerAreLabelledRatherThanLeftBlank(): void
	{
		$source = CompiledArtifact::source([]);

		$this->assertStringContainsString('// Compiled from: (unknown)', $source);
		$this->assertStringContainsString('// Generated by: (unknown)', $source);
	}

	/**
	 * No closing tag: trailing whitespace after one is output, which breaks header operations
	 * (session_start(), setcookie()) in worker mode.
	 */
	public function testTheArtifactHasNoClosingTag(): void
	{
		$this->assertStringNotContainsString('?>', CompiledArtifact::source(['a' => 1]));
	}

	/**
	 * @return array<string, array{mixed}>
	 */
	public static function declarationProvider(): array
	{
		return [
			'nested array' => [['a' => ['b' => [1, 2, 3]], 'c' => 'x']],
			'empty array' => [[]],
			'null' => [null],
			'false' => [false],
			'zero' => [0],
			'float' => [1.5],
			'string with quotes' => ["it's \"quoted\"\n"],
			'int keys' => [[0 => 'a', 5 => 'b']],
		];
	}

	#[\PHPUnit\Framework\Attributes\DataProvider('declarationProvider')]
	public function testADeclarationSurvivesTheRoundTripUnchanged(mixed $value): void
	{
		$this->assertSame($value, $this->roundTrip($value));
	}

	public function testAnObjectIsRejectedRatherThanWrittenAsSetState(): void
	{
		$this->expectException(CacheException::class);
		$this->expectExceptionMessageMatches('/declares a stdClass at its root/');
		CompiledArtifact::source(new \stdClass(), '/tmp/foo.xml', 'TestHandler');
	}

	/**
	 * The message has to say *where*: a declaration is a nested array, and "somewhere in this config
	 * there is an object" is not enough to find it.
	 */
	public function testANestedObjectIsRejectedAndItsKeyPathNamed(): void
	{
		$this->expectException(CacheException::class);
		$this->expectExceptionMessageMatches("/declares a Closure at key \\['a'\\]\\[0\\]\\['b'\\]/");
		CompiledArtifact::source(['a' => [['b' => static fn(): int => 1]]], '/tmp/foo.xml', 'TestHandler');
	}

	public function testAResourceIsRejected(): void
	{
		$handle = fopen('php://memory', 'rb');
		$this->assertNotFalse($handle);
		try {
			$this->expectException(CacheException::class);
			$this->expectExceptionMessageMatches('/declares a resource/');
			CompiledArtifact::source(['stream' => $handle], '/tmp/foo.xml', 'TestHandler');
		} finally {
			fclose($handle);
		}
	}
}
