<?php

// This is a compiled Agavi configuration file
// Compiled from: /home/markus/Projects/agavi/test/sandbox/app/Config//compile.xml
// Generated by: Agavi\Config\AgaviCompileConfigHandler
// Date: 2025-06-05T16:55:58+00:00



?>