<?php

// This is a compiled Agavi configuration file
// Compiled from: /home/markus/Projects/agavi/test/sandbox/app/Config//factories.xml
// Generated by: Agavi\Config\AgaviFactoryConfigHandler
// Date: 2025-06-05T16:55:58+00:00

$this->factories['execution_container'] = array (
  'class' => 'Agavi\\Controller\\AgaviExecutionContainer',
  'parameters' => 
  array (
  ),
);
$this->factories['validation_manager'] = array (
  'class' => 'Agavi\\Validator\\AgaviValidationManager',
  'parameters' => 
  array (
    'mode' => 'strict',
  ),
);
$this->factories['dispatch_filter'] = array (
  'class' => 'Agavi\\Filter\\AgaviDispatchFilter',
  'parameters' => 
  array (
  ),
);
$this->factories['execution_filter'] = array (
  'class' => 'Agavi\\Filter\\AgaviExecutionFilter',
  'parameters' => 
  array (
  ),
);
$this->factories['security_filter'] = array (
  'class' => 'Agavi\\Filter\\AgaviSecurityFilter',
  'parameters' => 
  array (
  ),
);
$this->factories['filter_chain'] = array (
  'class' => 'Agavi\\Filter\\AgaviFilterChain',
  'parameters' => 
  array (
  ),
);
$this->factories['response'] = array (
  'class' => 'Agavi\\Response\\AgaviWebResponse',
  'parameters' => 
  array (
  ),
);
$this->loggerManager = new Agavi\Logging\AgaviLoggerManager();
$this->loggerManager->initialize($this, array (
));
$this->loggerManager->startup();
$this->translationManager = new Agavi\Translation\AgaviTranslationManager();
$this->translationManager->initialize($this, array (
));
$this->request = new TestWebRequest();
$this->request->initialize($this, array (
  'sources' => 
  array (
    'SERVER_NAME' => 'localhost',
    'SERVER_PORT' => '80',
    'SERVER_PROTOCOL' => 'http',
  ),
));
$this->routing = new Agavi\Routing\AgaviWebRouting();
$this->routing->initialize($this, array (
));
$this->controller = new Agavi\Controller\AgaviController();
$this->controller->initialize($this, array (
));
$this->storage = new Agavi\Storage\AgaviNullStorage();
$this->storage->initialize($this, array (
));
$this->storage->startup();
$this->user = new Agavi\User\AgaviSecurityUser();
$this->user->initialize($this, array (
));
$this->translationManager->startup();
$this->user->startup();
$this->routing->startup();
$this->request->startup();
$this->controller->startup();
$this->shutdownSequence = [$this->controller,
$this->request,
$this->routing,
$this->user,
$this->translationManager,
$this->storage,
$this->loggerManager];

?>