<?php

// This is a compiled Agavi configuration file
// Compiled from: /home/markus/Projects/agavi/test/sandbox/app/Config//logging.xml
// Generated by: Agavi\Config\AgaviLoggingConfigHandler
// Date: 2025-06-05T16:55:58+00:00



?>