<?php

// This is a compiled Agavi configuration file
// Compiled from: /home/markus/Projects/agavi/test/sandbox/app/Config//output_types.xml
// Generated by: Agavi\Config\AgaviOutputTypeConfigHandler
// Date: 2025-06-05T16:55:58+00:00

$ot = new Agavi\Controller\AgaviOutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'text/html; charset=UTF-8',
  ),
), 'html', array (
  'php' => 
  array (
    'class' => 'Agavi\\Renderer\\AgaviPhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
      'assigns' => 
      array (
        'routing' => 'ro',
        'request' => 'rq',
        'controller' => 'ct',
        'user' => 'us',
        'translation_manager' => 'tm',
        'request_data' => 'rd',
      ),
    ),
  ),
), 'php', array (
  'default' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'Agavi\\View\\AgaviFileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
), 'default', NULL);
$this->outputTypes['html'] = $ot;
$ot = new Agavi\Controller\AgaviOutputType();
$ot->initialize($this->context, array (
), 'controllerTest', array (
  'php' => 
  array (
    'class' => 'Agavi\\Renderer\\AgaviPhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
    ),
  ),
), 'php', array (
), NULL, NULL);
$this->outputTypes['controllerTest'] = $ot;
$this->defaultOutputType = 'html';

?>