<?php

// This is a compiled Agavi configuration file
// Compiled from: /home/markus/Projects/agavi/test/sandbox/app/Config//settings.xml
// Generated by: Agavi\Config\AgaviSettingConfigHandler
// Date: 2025-06-05T16:55:58+00:00

Agavi\Config\AgaviConfig::fromArray(array (
  'actions.default_module' => 'Default',
  'actions.default_action' => 'Index',
  'actions.error_404_module' => 'Default',
  'actions.error_404_action' => 'Error404',
  'actions.unavailable_module' => 'Default',
  'actions.unavailable_action' => 'Unavailable',
  'actions.module_disabled_module' => 'Default',
  'actions.module_disabled_action' => 'ModuleDisabled',
  'actions.secure_module' => 'Default',
  'actions.secure_action' => 'Secure',
  'actions.login_module' => 'Default',
  'actions.login_action' => 'Login',
  'core.app_name' => 'sandbox',
  'core.available' => true,
  'core.debug' => true,
  'core.use_database' => false,
  'core.use_logging' => true,
  'core.use_security' => true,
  'core.use_translation' => true,
  'exception.default_template' => '/home/markus/Projects/agavi/src/Exception/templates/plaintext.php',
  'exception.templates.console' => '/home/markus/Projects/agavi/src/Exception/templates/plaintext.php',
  'core.default_context' => 'web',
));

?>