<?php
namespace Quiote\Config;

use Quiote\Util\ParameterHolder;
use Quiote\Util\Toolkit;

/**
 * BaseConfigHandler allows a developer to create a custom formatted
 * configuration file pertaining to any information they like and still
 * have it auto-generate PHP code.
 * @since      1.0.0
 * @version    1.0.0
 */
abstract class BaseConfigHandler extends ParameterHolder
{
	/**
	 * Generate the code for returning from execute().
	 * @param      mixed $code A string with the code, or an array of code lines.
	 * @param      ?string $path An optional config file path, to be put in a comment.
	 * @return     string PHP code.
	 * @since      1.0.0
	 */
	protected function generate($code, $path = null)
	{
		if(is_array($code)) {
			$code = implode("\n", $code);
		}
		
		// Intentionally omit the closing PHP tag to avoid accidental whitespace output
		// which can break header operations (e.g., session_start, setcookie) in worker mode.
		// We previously always appended an extra semicolon, which resulted in ';;' when the
		// provided code already ended with a semicolon (common, e.g. 'return array(...);').
		// Only append a semicolon if the last non-whitespace character is not one that
		// normally terminates a PHP statement or block.
		$trimmed = rtrim((string) $code);
		if($trimmed !== '' && !preg_match('/[;}\]]$/', $trimmed)) {
			$code = $trimmed . ';';
		} else {
			$code = $trimmed; // ensure consistent trailing whitespace handling
		}
		return sprintf(
			"<?php\n\n// This is a compiled Quiote configuration file\n// Compiled from: %s\n// Generated by: %s\n// Date: %s\n\n%s\n",
			$path ?? '(unknown)',
			static::class,
			gmdate(\DateTime::ATOM),
			$code
		);
	}
	
	/**
     * Literalize a string value.
     * @param      mixed $value The value to literalize.
     * @return     mixed A literalized value.
     * @phpstan-return ($value is string ? null|bool|int|float|string : mixed)
     * @since      1.0.0
     */
    #[\Deprecated(message: 'Use Toolkit::expandDirectives() instead.')]
    public static function literalize($value)
	{
		return Toolkit::literalize($value);
	}

	/**
     * Replace configuration directive identifiers in a string.
     * @param      string $value The value on which to run the replacement procedure.
     * @return     string The new value.
     * @since      1.0.0
     */
    #[\Deprecated(message: 'Use Toolkit::expandDirectives() instead.')]
    public static function replaceConstants($value)
	{
		// Toolkit::expandDirectives() only returns null for a null input, or on
		// a regex engine error; $value is a known non-null string here, so fall
		// back to it in that (effectively unreachable) failure case.
		return Toolkit::expandDirectives($value) ?? $value;
	}

	/**
	 * Replace a relative filesystem path with an absolute one.
	 * @param      string $path A relative filesystem path.
	 * @return     string The new path.
	 * @since      1.0.0
	 */
	public static function replacePath($path)
	{
		if(!Toolkit::isPathAbsolute($path)) {
			// not an absolute path so we'll prepend to it
			$path = Config::getString('core.app_dir') . '/' . $path;
		}

		return $path;
	}
}
