<?php

declare(strict_types=1);

namespace Quiote\Config;

use Quiote\Exception\CacheException;

/**
 * Serializes a config handler's declaration into the PHP file the on-disk cache holds.
 *
 * A handler produces data; how that data is stored is the cache's business, and this is the one place
 * that turns it into source. The file is a header comment plus a single `return <literal>;`, so the
 * only thing including it can ever do is hand back a value -- and, unlike an `eval()`'d string, it is
 * opcache-cacheable, so an unchanged config costs nothing to read again.
 *
 * @since      4.0.0
 */
final class CompiledArtifact
{
    /**
     * The PHP source for a compiled configuration file.
     *
     * @param      mixed $value The declaration the handler compiled.
     * @param      ?string $path The configuration file it came from, for the header comment.
     * @param      ?string $generatedBy The handler class that compiled it, for the header comment.
     * @return     string PHP source that returns $value.
     * @throws     CacheException If the declaration contains something no PHP literal can express.
     * @since      4.0.0
     */
    public static function source(mixed $value, ?string $path = null, ?string $generatedBy = null): string
    {
        // The closing PHP tag is intentionally omitted: trailing whitespace after it is output, which
        // breaks header operations (session_start(), setcookie()) in worker mode.
        return sprintf(
            "<?php\n\n// This is a compiled Quiote configuration file\n// Compiled from: %s\n// Generated by: %s\n// Date: %s\n\n%s\n",
            $path ?? '(unknown)',
            $generatedBy ?? '(unknown)',
            gmdate(\DateTime::ATOM),
            'return ' . self::literal($value, $path) . ';'
        );
    }

    /**
     * A declaration as a PHP literal.
     *
     * `var_export()` emits `\ClassName::__set_state(...)` for an object and warns-and-emits `NULL` for
     * a resource, neither of which round-trips -- so a handler returning one is rejected here, where
     * the handler and its source file can still be named, rather than at the include that fails to
     * reproduce it.
     *
     * @throws     CacheException If the value is not expressible as a literal.
     * @since      4.0.0
     */
    private static function literal(mixed $value, ?string $path): string
    {
        self::assertExpressible($value, $path, '');

        return var_export($value, true);
    }

    /**
     * @param      string $where The path to the offending value inside the declaration.
     * @throws     CacheException
     * @since      4.0.0
     */
    private static function assertExpressible(mixed $value, ?string $path, string $where): void
    {
        if (is_array($value)) {
            foreach ($value as $key => $item) {
                self::assertExpressible($item, $path, $where . '[' . var_export($key, true) . ']');
            }

            return;
        }

        if ($value === null || is_scalar($value)) {
            return;
        }

        throw new CacheException(sprintf(
            'The configuration compiled from "%s" declares a %s at %s. A compiled configuration must be '
            . 'data a PHP literal can express: scalars, null and arrays of those.',
            $path ?? '(unknown)',
            get_debug_type($value),
            $where === '' ? 'its root' : 'key ' . $where
        ));
    }
}
