<?php

// This is a compiled Quiote configuration file
// Compiled from: /home/markus/Projects/agavi/tests/sandbox/app/Config//config_handlers.xml
// Generated by: Quiote\Config\ConfigHandlersConfigHandler
// Date: 2026-07-01T22:35:15+00:00

return array (
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//settings.xml' => 
  array (
    'class' => 'Quiote\\Config\\SettingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/settings.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/settings.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/settings.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//factories.xml' => 
  array (
    'class' => 'Quiote\\Config\\FactoryConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/factories.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/factories.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/factories.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//databases.xml' => 
  array (
    'class' => 'Quiote\\Config\\DatabaseConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/databases.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/databases.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/databases.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//action_filters.xml' => 
  array (
    'class' => 'Quiote\\Config\\FilterConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/filters.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/filters.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/filters.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//global_filters.xml' => 
  array (
    'class' => 'Quiote\\Config\\FilterConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/filters.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/filters.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/filters.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//output_types.xml' => 
  array (
    'class' => 'Quiote\\Config\\OutputTypeConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/output_types.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/output_types.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/output_types.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//rbac_definitions.xml' => 
  array (
    'class' => 'Quiote\\Config\\RbacDefinitionConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/rbac_definitions.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/rbac_definitions.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/rbac_definitions.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//routing.xml' => 
  array (
    'class' => 'Quiote\\Config\\RoutingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/routing.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/routing.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/routing.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/Quiote/routing/soap/wsdl.xml' => 
  array (
    'class' => 'Quiote\\Config\\WsdlConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/routing.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/routing.xsl',
      ),
      'compilation' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Routing/soap/wsdl.xsl',
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//translation.xml' => 
  array (
    'class' => 'Quiote\\Config\\TranslationConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/translation.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/translation.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/translation.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/Config/suites.xml' => 
  array (
    'class' => 'Quiote\\Config\\TestSuitesConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/testing.suites.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Modules/*/Config/action_filters.xml' => 
  array (
    'class' => 'Quiote\\Config\\FilterConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/filters.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/filters.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/filters.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Modules/*/Config/module.xml' => 
  array (
    'class' => 'Quiote\\Config\\ModuleConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/module.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/module.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/module.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Modules/*/Validate/*.xml' => 
  array (
    'class' => 'Quiote\\Config\\ValidatorConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/validators.xsl',
        1 => '/home/markus/Projects/agavi/Quiote/Config/xsl/validators.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/validators.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  'confighandler-testing' => 
  array (
    'class' => 'ReturnArrayConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => 'confighandler-testing.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
            0 => 'confighandler-testing.rng',
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//tests/importtest.xml' => 
  array (
    'class' => 'ImportTestHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//tests/importtest_once.xml' => 
  array (
    'class' => 'ImportTestOnceHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/home/markus/Projects/agavi/tests/sandbox/app/Config//tests/routing_*.xml' => 
  array (
    'class' => 'Quiote\\Config\\RoutingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/home/markus/Projects/agavi/Quiote/Config/xsl/routing.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/home/markus/Projects/agavi/Quiote/Config/xsd/routing.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
);
