<?php

// This is a compiled Quiote configuration file
// Compiled from: /home/markus/Projects/agavi/tests/sandbox/app/Config//databases.xml
// Generated by: Quiote\Config\DatabaseConfigHandler
// Date: 2026-07-02T06:31:26+00:00

$database = new Quiote\Database\PdoDatabase();
$this->databases['pdo_mysql_main'] = $database;
$database->initialize($this, array (
  'dsn' => 'mysql:host=localhost;dbname=agsmplapp',
  'username' => 'root',
  'password' => NULL,
));
$this->defaultDatabaseName = 'pdo_mysql_main';
