<?php

// This is a compiled Quiote configuration file
// Compiled from: /home/markus/Projects/agavi/tests/sandbox/app/Config//factories.xml
// Generated by: Quiote\Config\FactoryConfigHandler
// Date: 2026-07-01T22:35:15+00:00

$this->factories['validation_manager'] = array (
  'class' => 'Quiote\\Validator\\ValidationManager',
  'parameters' => 
  array (
    'mode' => 'strict',
  ),
);
$this->factories['validation_manager']['factory_info'] = array (
  'class' => 'Quiote\\Validator\\ValidationManager',
  'parameters' => 
  array (
    'mode' => 'strict',
  ),
);
$this->factories['response'] = array (
  'class' => 'Quiote\\Response\\WebResponse',
  'parameters' => 
  array (
  ),
);
$this->factories['response']['factory_info'] = array (
  'class' => 'Quiote\\Response\\WebResponse',
  'parameters' => 
  array (
  ),
);
$this->databaseManager = new Quiote\Database\DatabaseManager();
$this->databaseManager->initialize($this, array (
));
$this->databaseManagerFactoryInfo = ['class' => 'Quiote\\Database\\DatabaseManager', 'parameters' => array (
)];
$this->databaseManager->startup();
$this->translationManager = new Quiote\Translation\TranslationManager();
$this->translationManager->initialize($this, array (
));
$this->translationManagerFactoryInfo = ['class' => 'Quiote\\Translation\\TranslationManager', 'parameters' => array (
)];
$this->routing = new Sandbox\App\Routing\SandboxRouting();
$this->routing->initialize($this, array (
));
$this->routingFactoryInfo = ['class' => 'Sandbox\\App\\Routing\\SandboxRouting', 'parameters' => array (
)];
$this->request = new Sandbox\Lib\Request\TestWebRequest();
$this->request->initialize($this, array (
  'sources' => 
  array (
    'SERVER_NAME' => 'localhost',
    'SERVER_PORT' => '80',
    'SERVER_PROTOCOL' => 'http',
  ),
));
$this->requestFactoryInfo = ['class' => 'Sandbox\\Lib\\Request\\TestWebRequest', 'parameters' => array (
  'sources' => 
  array (
    'SERVER_NAME' => 'localhost',
    'SERVER_PORT' => '80',
    'SERVER_PROTOCOL' => 'http',
  ),
)];
$this->controller = new Quiote\Controller\Controller();
$this->controller->initialize($this, array (
));
$this->controllerFactoryInfo = ['class' => 'Quiote\\Controller\\Controller', 'parameters' => array (
)];
$this->storage = new Quiote\Storage\NullStorage();
$this->storage->initialize($this, array (
));
$this->storageFactoryInfo = ['class' => 'Quiote\\Storage\\NullStorage', 'parameters' => array (
)];
$this->storage->startup();
$this->user = new Quiote\User\SecurityUser();
$this->user->initialize($this, array (
));
$this->userFactoryInfo = ['class' => 'Quiote\\User\\SecurityUser', 'parameters' => array (
)];
$this->translationManager->startup();
$this->user->startup();
$this->routing->startup();
$this->controller->startup();
$this->shutdownSequence = [$this->controller,
$this->routing,
$this->user,
$this->translationManager,
$this->storage,
$this->databaseManager];
