<?php

// This is a compiled Quiote configuration file
// Compiled from: /home/markus/Projects/agavi/tests/sandbox/app/Config//output_types.xml
// Generated by: Quiote\Config\OutputTypeConfigHandler
// Date: 2026-07-01T22:35:15+00:00

$ot = new Quiote\Controller\OutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'text/html; charset=UTF-8',
  ),
), 'html', array (
  'php' => 
  array (
    'class' => 'Quiote\\Renderer\\PhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
      'assigns' => 
      array (
        'routing' => 'ro',
        'request' => 'rq',
        'controller' => 'ct',
        'user' => 'us',
        'translation_manager' => 'tm',
        'request_data' => 'rd',
      ),
    ),
  ),
), 'php', array (
  'default' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'Quiote\\View\\FileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
), 'default', NULL);
$this->outputTypes['html'] = $ot;
$ot = new Quiote\Controller\OutputType();
$ot->initialize($this->context, array (
), 'controllerTest', array (
  'php' => 
  array (
    'class' => 'Quiote\\Renderer\\PhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
    ),
  ),
), 'php', array (
), NULL, NULL);
$this->outputTypes['controllerTest'] = $ot;
$ot = new Quiote\Controller\OutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'application/json; charset=UTF-8',
  ),
), 'json', array (
  'php' => 
  array (
    'class' => 'Quiote\\Renderer\\PhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
    ),
  ),
), 'php', array (
), NULL, NULL);
$this->outputTypes['json'] = $ot;
$ot = new Quiote\Controller\OutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'application/xml; charset=UTF-8',
  ),
), 'xml', array (
  'php' => 
  array (
    'class' => 'Quiote\\Renderer\\PhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
    ),
  ),
), 'php', array (
), NULL, NULL);
$this->outputTypes['xml'] = $ot;
$ot = new Quiote\Controller\OutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'application/vnd.ms-excel; charset=UTF-8',
  ),
), 'xls', array (
  'php' => 
  array (
    'class' => 'Quiote\\Renderer\\PhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
    ),
  ),
), 'php', array (
), NULL, NULL);
$this->outputTypes['xls'] = $ot;
$this->defaultOutputType = 'html';
