<?php

declare(strict_types=1);

use PHPUnit\Framework\TestCase;
use Agavi\Routing\AgaviRouting;
use Symfony\Component\Routing\RouteCollection;
use Symfony\Component\Routing\Route;

final class AgaviRoutingOmitDefaultsEdgeTest extends TestCase
{
    private function routing(array $spec): AgaviRouting
    {
        return new class($spec) extends AgaviRouting {
            public function __construct(private array $spec) { parent::__construct(); }
            protected function build(): array {
                $rc = new RouteCollection();
                $meta = [];
                foreach ($this->spec as $name => $r) {
                    $pattern = $r['pattern'];
                    $defaults = $r['defaults'] ?? [];
                    $rc->add($name, new Route($pattern, $defaults));
                    $meta[$name] = [
                        'gen_path' => $pattern,
                        'cut' => false,
                        'path' => $pattern,
                        'match_full' => '#^' . trim($pattern,'^') . '$#',
                        'match_partial' => '#^' . trim($pattern,'^') . '#',
                        'opt' => [
                            'parent' => null,
                            'action' => $defaults['action'] ?? null,
                        ]
                    ];
                }
                return [$rc, $meta];
            }
        };
    }

    public function testFullSuffixAllDefaultsPruned()
    {
        $r = $this->routing([
            'all_def' => ['pattern' => '/a/{x}/{y}', 'defaults' => ['x' => 'dx', 'y' => 'dy']]
        ]);
        $this->assertSame('/a/dx/dy', $r->gen('all_def'));
        $this->assertSame('/a', $r->gen('all_def', [], ['omit_defaults' => true]));
    }

    public function testBarrierStopsFurtherLeftPruning()
    {
        $r = $this->routing([
            'barrier' => ['pattern' => '/a/{x}/{y}/{z}/{q}', 'defaults' => ['x' => 'dx','y' => 'dy','z' => 'dz','q' => 'dq']]
        ]);
        // Provide non-default for z; current pruning logic stops at first non-default scanning from the right, so q remains.
        $url = $r->gen('barrier', ['z' => 'ZZ'], ['omit_defaults' => true]);
        $this->assertSame('/a/dx/dy/ZZ/dq', $url);
        // Without omit_defaults full path identical
        $full = $r->gen('barrier', ['z' => 'ZZ']);
        $this->assertSame('/a/dx/dy/ZZ/dq', $full);
    }

    public function testEarlierDefaultRetainedWhenMiddleDiffers()
    {
        $r = $this->routing([
            'combo' => ['pattern' => '/a/{x}/{y}/{z}', 'defaults' => ['x' => 'dx','y' => 'dy','z' => 'dz']]
        ]);
        $url = $r->gen('combo', ['y' => 'Y!'], ['omit_defaults' => true]);
        $this->assertSame('/a/dx/Y!/dz', $url);
    }

    public function testEncodingPreservationWithExclamation()
    {
        $r = $this->routing([
            'enc' => ['pattern' => '/f/{name}/{lang}', 'defaults' => ['name' => 'file!','lang' => 'en']]
        ]);
        // Both defaults removed -> /f
        $this->assertSame('/f', $r->gen('enc', [], ['omit_defaults' => true]));
        // Override name only; lang default remains and is trailing so subject to pruning with omit_defaults on.
        $this->assertSame('/f/custom!', $r->gen('enc', ['name' => 'custom!'], ['omit_defaults' => true]));
        // Raw generation keeps the default segment for lang
        $this->assertSame('/f/custom!/en', $r->gen('enc', ['name' => 'custom!']));
        // Space encoded + ! preserved
        $u = $r->gen('enc', ['name' => 'my file!'], ['omit_defaults' => true]);
        $this->assertSame('/f/my%20file!', $u);
    }

    public function testAutoGeneratedNamesUnique()
    {
        // Start with empty routing and add routes via addRoute without names
        $r = $this->routing([]);
        $n1 = $r->addRoute('/alpha');
        $n2 = $r->addRoute('/beta');
        $n3 = $r->addRoute('/gamma');
        $this->assertNotSame($n1, $n2);
        $this->assertNotSame($n2, $n3);
        $this->assertNotSame($n1, $n3);
        // Ensure generation works
        $this->assertSame('/alpha', $r->gen($n1));
        $this->assertSame('/beta', $r->gen($n2));
        $this->assertSame('/gamma', $r->gen($n3));
    }
}
