name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: dom, intl, xsl, tokenizer, session, pdo, pdo_sqlite, iconv, mbstring
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: vendor/bin/phpunit -c tests/config/phpunit.xml
