<?php

// This is a compiled Quiote configuration file
// Compiled from: /app/Quiote/Config/defaults/config_handlers.xml
// Generated by: Quiote\Config\ConfigHandlersConfigHandler
// Date: 2026-07-02T12:38:49+00:00

return array (
  '/app/samples/app/Config/settings.xml' => 
  array (
    'class' => 'Quiote\\Config\\SettingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/app/Quiote/Config/xsl/settings.xsl',
        1 => '/app/Quiote/Config/xsl/settings.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/app/Quiote/Config/xsd/settings.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/app/samples/app/Config/factories.xml' => 
  array (
    'class' => 'Quiote\\Config\\FactoryConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/app/Quiote/Config/xsl/factories.xsl',
        1 => '/app/Quiote/Config/xsl/factories.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/app/Quiote/Config/xsd/factories.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/app/samples/app/Config/databases.xml' => 
  array (
    'class' => 'Quiote\\Config\\DatabaseConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/app/Quiote/Config/xsl/databases.xsl',
        1 => '/app/Quiote/Config/xsl/databases.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/app/Quiote/Config/xsd/databases.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/app/samples/app/Config/output_types.xml' => 
  array (
    'class' => 'Quiote\\Config\\OutputTypeConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/app/Quiote/Config/xsl/output_types.xsl',
        1 => '/app/Quiote/Config/xsl/output_types.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/app/Quiote/Config/xsd/output_types.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/app/samples/app/Config/rbac_definitions.xml' => 
  array (
    'class' => 'Quiote\\Config\\RbacDefinitionConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/app/Quiote/Config/xsl/rbac_definitions.xsl',
        1 => '/app/Quiote/Config/xsl/rbac_definitions.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/app/Quiote/Config/xsd/rbac_definitions.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/app/samples/app/Config/routing.xml' => 
  array (
    'class' => 'Quiote\\Config\\RoutingConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/app/Quiote/Config/xsl/routing.xsl',
        1 => '/app/Quiote/Config/xsl/routing.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/app/Quiote/Config/xsd/routing.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/app/samples/app/Config/translation.xml' => 
  array (
    'class' => 'Quiote\\Config\\TranslationConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/app/Quiote/Config/xsl/translation.xsl',
        1 => '/app/Quiote/Config/xsl/translation.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/app/Quiote/Config/xsd/translation.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '%core.testing_dir%/Config/suites.xml' => 
  array (
    'class' => 'Quiote\\Config\\TestSuitesConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/app/Quiote/Config/xsl/testing.suites.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/app/samples/app/Modules/*/Config/module.xml' => 
  array (
    'class' => 'Quiote\\Config\\ModuleConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/app/Quiote/Config/xsl/module.xsl',
        1 => '/app/Quiote/Config/xsl/module.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/app/Quiote/Config/xsd/module.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
  '/app/samples/app/Modules/*/Validate/*.xml' => 
  array (
    'class' => 'Quiote\\Config\\ValidatorConfigHandler',
    'parameters' => 
    array (
    ),
    'transformations' => 
    array (
      'single' => 
      array (
        0 => '/app/Quiote/Config/xsl/validators.xsl',
        1 => '/app/Quiote/Config/xsl/validators.xsl',
      ),
      'compilation' => 
      array (
      ),
    ),
    'validations' => 
    array (
      'single' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
            0 => '/app/Quiote/Config/xsd/validators.xsd',
          ),
        ),
      ),
      'compilation' => 
      array (
        'transformations_before' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
        'transformations_after' => 
        array (
          'relax_ng' => 
          array (
          ),
          'schematron' => 
          array (
          ),
          'xml_schema' => 
          array (
          ),
        ),
      ),
    ),
  ),
);
