<?php

// This is a compiled Quiote configuration file
// Compiled from: /app/samples/app/Config/databases.xml
// Generated by: Quiote\Config\DatabaseConfigHandler
// Date: 2026-07-02T12:38:49+00:00

$database = new Quiote\Database\PdoDatabase();
$this->databases['default'] = $database;
$database->initialize($this, array (
  'dsn' => 'sqlite::memory:',
));
$this->defaultDatabaseName = 'default';
