<?php

// This is a compiled Quiote configuration file
// Compiled from: /app/samples/app/Config/factories.yaml
// Generated by: Quiote\Config\FactoryConfigHandler
// Date: 2026-07-02T12:38:49+00:00

$this->factories['validation_manager'] = array (
  'class' => 'Quiote\\Validator\\ValidationManager',
  'parameters' => 
  array (
  ),
);
$this->factories['validation_manager']['factory_info'] = array (
  'class' => 'Quiote\\Validator\\ValidationManager',
  'parameters' => 
  array (
  ),
);
$this->factories['response'] = array (
  'class' => 'Quiote\\Response\\WebResponse',
  'parameters' => 
  array (
  ),
);
$this->factories['response']['factory_info'] = array (
  'class' => 'Quiote\\Response\\WebResponse',
  'parameters' => 
  array (
  ),
);
$this->databaseManager = new Quiote\Database\DatabaseManager();
$this->databaseManager->initialize($this, array (
));
$this->databaseManagerFactoryInfo = ['class' => 'Quiote\\Database\\DatabaseManager', 'parameters' => array (
)];
$this->databaseManager->startup();
$this->routing = new SampleApp\Routing\AppRouting();
$this->routing->initialize($this, array (
));
$this->routingFactoryInfo = ['class' => 'SampleApp\\Routing\\AppRouting', 'parameters' => array (
)];
$this->request = new Quiote\Request\WebRequest();
$this->request->initialize($this, array (
));
$this->requestFactoryInfo = ['class' => 'Quiote\\Request\\WebRequest', 'parameters' => array (
)];
$this->controller = new Quiote\Controller\Controller();
$this->controller->initialize($this, array (
));
$this->controllerFactoryInfo = ['class' => 'Quiote\\Controller\\Controller', 'parameters' => array (
)];
$this->storage = new Quiote\Storage\NullStorage();
$this->storage->initialize($this, array (
));
$this->storageFactoryInfo = ['class' => 'Quiote\\Storage\\NullStorage', 'parameters' => array (
)];
$this->storage->startup();
$this->user = new Quiote\User\User();
$this->user->initialize($this, array (
));
$this->userFactoryInfo = ['class' => 'Quiote\\User\\User', 'parameters' => array (
)];
$this->user->startup();
$this->routing->startup();
$this->controller->startup();
$this->shutdownSequence = [$this->controller,
$this->routing,
$this->user,
$this->storage,
$this->databaseManager];
