<?php

// This is a compiled Quiote configuration file
// Compiled from: /app/samples/app/Config/output_types.xml
// Generated by: Quiote\Config\OutputTypeConfigHandler
// Date: 2026-07-02T12:38:49+00:00

$ot = new Quiote\Controller\OutputType();
$ot->initialize($this->context, array (
  'http_headers' => 
  array (
    'Content-Type' => 'text/html; charset=UTF-8',
  ),
), 'html', array (
  'php' => 
  array (
    'class' => 'Quiote\\Renderer\\PhpRenderer',
    'instance' => NULL,
    'parameters' => 
    array (
    ),
  ),
), 'php', array (
  'default' => 
  array (
    'layers' => 
    array (
      'content' => 
      array (
        'class' => 'Quiote\\View\\FileTemplateLayer',
        'parameters' => 
        array (
        ),
        'renderer' => NULL,
        'slots' => 
        array (
        ),
      ),
    ),
    'parameters' => 
    array (
    ),
  ),
), 'default', NULL);
$this->outputTypes['html'] = $ot;
$this->defaultOutputType = 'html';
