<?php

// This is a compiled Quiote configuration file
// Compiled from: /app/samples/app/Config/settings.php
// Generated by: Quiote\Config\SettingConfigHandler
// Date: 2026-07-02T12:38:49+00:00

Quiote\Config\Config::fromArray(array (
  'core.app_name' => 'SampleApp',
  'core.namespace_prefix' => 'SampleApp',
  'core.available' => true,
  'core.debug' => false,
  'core.use_database' => false,
  'core.use_logging' => true,
  'core.use_security' => false,
  'core.use_translation' => false,
  'core.default_context' => 'web',
));
